services:
  be:
    build:
      context: .
      dockerfile: ./be/Dockerfile
    tty: true
    volumes:
      - ./be:/app
    ports:
      - 3030:3030
    networks:
      - backend
  fe:
    build:
      context: .
      dockerfile: ./fe/Dockerfile
    tty: true
    volumes:
      - ./fe:/app
    ports:
      - 8000:8000
    networks:
      - backend
networks:
  backend:
    ipam:
     driver: default
     config:
       - subnet: 192.168.0.0/24