services:
  be:
    build:
      context: .
      dockerfile: ./be/Dockerfile
    tty: true
    volumes:
      - ./be:/app
    ports:
      - 3030:3030
  fe:
    build:
      context: .
      dockerfile: ./fe/Dockerfile
    tty: true
    volumes:
      - ./fe:/app
    ports:
      - 8000:8000